# These are supported funding model platforms

github: [julien-nc]# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
liberapay: 'eneiluj'# Replace with a single Liberapay username
custom: ['https://www.paypal.com/donate/?hosted_button_id=BHC6KJW4HBT3E']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
